### ISSUE TITLE
Write a better readme

### ISSUE THREAD

**Issue by boobo94** [MatthiasMargot/organigram#1]
Hi @MatthiasMargot ,

The tool it's really nice and I hope this will be a top starred module.

But, can you please be more poetic in the readme ? Maybe to explain a little bit how to do it, to have an introduction, because right now it's more for someone which used it before.

Thanks,
Boobo

**Comment by MatthiasMargot** [comment]
The only api that is currently exposed is the nesting structure, there really are no other ways/features to use it.

What would you have liked it to say more than that? The rendered output corresponds  1:1 with the code written below (provided you wrote the css for the colors boxes of course, since they are custom elements that arent part of the library)

**Comment by boobo94** [comment]
Is not about how much you explained the code, it's about visibility. I really prefer more a cleaner wiki with a good architecture, with answers to some question or some:

- what offers ?
- how solve my problem or my need ?
- a simple example

The informations offered by you are enough, but I'd like to have a better overview. It's all about how approachable is.

Refference

* [1] https://gist.github.com/PurpleBooth/109311bb0361f32d87a2

**Comment by MatthiasMargot** [comment]
I know what you mean, but this isn't published on npm yet + it's a very initial stage of this project (hopefully I can make this much cooler) and I will take care of it as soon as it gets to be something you'd prefer installing over writing yourself.

**Comment by boobo94** [comment]
good job 👍
